# -*- mode: ruby -*-
# vi: set ft=ruby :

unless Vagrant.has_plugin?("vagrant-hosts")
        system('vagrant plugin install vagrant-hosts')
        raise("Plugin installed. Run command again.");
end

$script = <<SCRIPT
sudo su
cd /vagrant/buildfarm_deployment_config
./install_prerequisites.bash
./reconfigure.bash $1
SCRIPT

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.define "master" do |master|
    master.vm.network "private_network", ip: "192.168.42.11"
    master.vm.provision :hosts
    master.vm.box = "ubuntu/trusty64"
    master.vm.provision "shell" do |s|
        s.inline = $script
        s.args   = "master"
    end
  end

 config.vm.define "repo" do |repo|
    repo.vm.network "private_network", ip: "192.168.42.22"
    repo.vm.provision :hosts
    repo.vm.box = "ubuntu/trusty64"
    repo.vm.provision "shell" do |s|
        s.inline = $script
        s.args   = "repo"
    end
  end

  config.vm.define "slave" do |slave|
    slave.vm.network "private_network", ip: "192.168.42.33"
    slave.vm.provision :hosts
    slave.vm.box = "ubuntu/trusty64"
    slave.vm.provision "shell" do |s|
        s.inline = $script
        s.args   = "slave"
    end
    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "4096"]
    end
  end
end
